* Encoding: UTF-8.

DATASET ACTIVATE ConjuntoDatos3.
EXAMINE VARIABLES=altura_metros
  /PLOT BOXPLOT STEMLEAF NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

T-TEST
  /TESTVAL=1.67
  /MISSING=ANALYSIS
  /VARIABLES=altura_metros
  /ES DISPLAY(FALSE)
  /CRITERIA=CI(.95).
